accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard_single/', views.dashboard_single, name='dashboard_single'),
    path('', views.dashboard, name='dashboard'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),

    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPasswordResetValidate/<uidb64>/<token>/', views.forgotPasswordResetValidate, name='forgotPasswordResetValidate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('forgotPasswordReset_page/', views.forgotPasswordReset_page, name='forgotPasswordReset_page'),

    path('<int:user_id>/', views.account_view, name="view"),#needed fot chat
    path('<int:user_id>/edit/cropImage/', views.crop_image, name="crop_image"),
    path('my_store_order/', views.my_store_order, name='my_store_order'),


]

carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('reduce_cart/<int:product_id>/<int:cart_item_id>/', views.reduce_cart, name='reduce_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

shopme/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
import store


urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('passage/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('currencies/', include('currencies.urls')),
    path('chatapp/', include('chatapp.urls')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('seller/', views.seller_doc, name='seller_doc'),
    path('services/', views.services_doc, name='services_doc'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #for media folder files access

orders/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, Variation

# Create your models here.
class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100) #transactionID
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id


#to record every order executed by batch
class Order(models.Model):

    STATUS = (
        # ('New', 'New'),
        ('Pending', 'Pending'),
        # ('Out for delivery', 'Out for delivery'),
        # ('Delivered', 'Delivered'),
        ('Cancelled', 'Cancelled'),
        ('Sent', 'Sent'),
        ('Customer deleted item' , 'Customer deleted item' ),
        ('PAID' , 'PAID'),
        ('Done Refund' , 'Done Refund')
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=21)
    first_name = models.CharField(max_length=54)
    last_name = models.CharField(max_length=54)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=51)
    address_line_1 = models.CharField(max_length=51)
    address_line_2 = models.CharField(max_length=51, blank=True)
    country = models.CharField(max_length=54)
    state = models.CharField(max_length=54)
    city = models.CharField(max_length=54)
    zip = models.IntegerField(null=True, blank=True)
    order_note = models.CharField(max_length=200, blank=True)
    currency = models.CharField(max_length=10, blank=True)
    item_count = models.IntegerField(null=True)
    order_total = models.FloatField()
    shipping = models.FloatField(null=True)
    recieved = models.BooleanField(default=False)
    tax = models.FloatField()
    status = models.CharField(max_length=25, choices=STATUS, default='Pending')
    ip = models.CharField(max_length=21, blank=True)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def fullname(self):
        return f'{self.first_name} {self.last_name}'

    def address(self):
        return f'{self.address_line_1} {self.address_line_2}, {self.city}, {self.state}, {self.country}, {self.zip}'

    def __unicode__(self):
        return self.user.username


#to record every order executed by item
class OrderProduct(models.Model):
    STATUS = (
        # ('New', 'New'),
        ('Pending', 'Pending'),
        # ('Out for delivery', 'Out for delivery'),
        # ('Delivered', 'Delivered'),
        ('Cancelled', 'Cancelled'),
        ('Sent', 'Sent'),
        ('Customer deleted item' , 'Customer deleted item' ),
        ('PAID' , 'PAID' ),
        ('Done Refund' , 'Done Refund')

    )

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    total_price = models.FloatField(default=1)
    ordered = models.BooleanField(default=False)
    status = models.CharField(max_length=25, null=True, choices = STATUS, default='Pending')
    ip = models.CharField(max_length=21, blank=True)
    recieved = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)
    for_payment =  models.BooleanField(default=False)
    request_payment =  models.BooleanField(default=False)
    cus_ref_accept_del = models.BooleanField(default=False)
    is_refund = models.BooleanField(default=False)
    cus_item_delete = models.BooleanField(default=False)


    def __str__(self):
        return self.product.product_name

    def date_updated(self):
        return self.updated_at.strftime('%B %d %Y') #converting to Month name, day and Year pattern

accounts/forms.py
from django import forms
from .models import Account
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _
from django.core.validators import RegexValidator
import re
from django.shortcuts import render

class RegistrationForm(forms.ModelForm):
    alphabet_fname  = RegexValidator(r'^[a-zA-Z]*$', 'Only letters are allowed in first name.')
    alphabet_lname  = RegexValidator(r'^[a-zA-Z]*$', 'Only letters are allowed in last name.')
    first_name      =forms.CharField(min_length=1, max_length=50, help_text='Required', validators=[alphabet_fname])
    last_name       =forms.CharField(min_length=1, max_length=50, help_text='Required', validators=[alphabet_lname])
    email           =forms.EmailField(max_length=100, help_text='Required')
    phone           =forms.CharField(max_length=50)
    password        = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter Password'}))
    confirm_password= forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone', 'email', 'password', 'confirm_password', 'country']

    def clean_confirm_password(self):
        cd=super(RegistrationForm, self).clean()
        if cd['password'] != cd['confirm_password']:
            raise ValidationError(
                _('Password do not match.'),
                code='password_no_matched1',
            )
        if len(cd['password']) < 6:
            raise ValidationError(
                _('Password must be at least 6 characters.'),
                code='password_too_short1',
            )
        if not re.findall('[A-Z]', cd['password']):
            raise ValidationError(
                _("The password must contain uppercase letters"),
                code='password_no_upper1',
            )
        if not re.findall('[a-z]', cd['password']):
            raise ValidationError(
                _("The password must contain lowercase letters"),
                code='password_no_lower1',
            )
        if not re.findall('\d', cd['password']):
            raise ValidationError(
                _("The password must contain at least 1 digit, 0-9."),
                code='password_no_number1',
            )
        if not re.findall('[()[\]{}|\\`~!@#$%^&*_\-+=;:\'",<>./?]', cd['password']):
            raise ValidationError(
                _("The password must contain at least 1 symbol: " +
                  "()[]{}|\`~!@#$%^&*_-+=;:'\",<>./?"),
                code='password_no_symbol1',
            )
        return cd['confirm_password']


    def __init__(self, *args, **kwargs): #to override the funtianlity of this particular form
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['phone'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].widget.attrs['style'] = 'height:42px;box-shadow: none !important;border-radius: 3px;height: 41px;outline: none !important;border-color: #a79b9b;'


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter Password'}))
    class Meta:
        model = Account
        fields = ['email', 'password']

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email'

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].widget.attrs['style'] = 'height:42px;box-shadow: none !important;border-radius: 3px;height: 41px;outline: none !important;border-color: #a79b9b;'


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'email', 'phone', 'profession', 'address_line_1', 'address_line_2', 'country', 'state', 'city', 'zip']

    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class CheckoutForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'email', 'phone', 'address_line_1', 'address_line_2', 'country', 'state', 'city', 'zip']

    def __init__(self, *args, **kwargs):
        super(CheckoutForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

        self.fields['city'].required =True
        self.fields['state'].required =True
        self.fields['country'].required =True

class UserProfilePicForm(forms.ModelForm):
    profile_pic = forms.ImageField(required=False, error_messages = {'invalid':("Image files only")}, widget=forms.FileInput)

    class Meta:
        model = Account
        fields = ['profile_pic']

    def __init__(self, *args, **kwargs):
        super(UserProfilePicForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control d-none'
            self.fields[field].widget.attrs['onchange'] = 'readURL(this)'
            self.fields[field].widget.attrs['name'] = 'profile_pic'
            self.fields[field].widget.attrs['id'] = 'id_profile_image'

class PwdChangeForm(forms.ModelForm): #we need to put validation because the default is lacking
    old_password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter Old Password'}))
    new_password1=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter New Password'}))
    new_password2=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm New Password'}))

    class Meta:
        model=Account
        fields=['old_password', 'new_password1', 'new_password2']

    def __init__(self, *args, **kwargs):
        super(PwdChangeForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean_new_password2(self):
        cd=self.cleaned_data
        if cd['new_password1'] != cd['new_password2']:
            raise ValidationError(
                _('Password do not match.'),
                code='password_no_matched1',
            )
        if len(cd['new_password1']) < 6:
            raise ValidationError(
                _('Password must be at least 6 characters.'),
                code='password_too_short1',
            )
        if not re.findall('[A-Z]', cd['new_password1']):
            raise ValidationError(
                _("The password must contain uppercase letters"),
                code='password_no_upper1',
            )
        if not re.findall('[a-z]', cd['new_password1']):
            raise ValidationError(
                _("The password must contain lowercase letters"),
                code='password_no_lower1',
            )
        if not re.findall('\d', cd['new_password1']):
            raise ValidationError(
                _("The password must contain at least 1 digit, 0-9."),
                code='password_no_number1',
            )
        if not re.findall('[()[\]{}|\\`~!@#$%^&*_\-+=;:\'",<>./?]', cd['new_password1']):
            raise ValidationError(
                _("The password must contain at least 1 symbol: " +
                  "()[]{}|\`~!@#$%^&*_-+=;:'\",<>./?"),
                code='password_no_symbol1',
            )
        return cd['new_password2']

orders/forms.py
from django import forms
from .models import Order, OrderProduct

class OrderForm(forms.ModelForm):
    zip  = forms.CharField(min_length=1, max_length=50, help_text='Required')
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'email', 'address_line_1', 'address_line_2', 'country', 'state', 'city', 'zip', 'currency', 'item_count', 'order_note']

class OrderStatusForm(forms.ModelForm):

    # this is needed if the django vatiabble form is not provided in the html file. using both will duplicate the item
    status = forms.CharField(max_length=25)
    class Meta:
        model = OrderProduct
        fields = ['status']

    def __init__(self, *args, **kwargs): #to override the funtianlity of this particular form
        super(OrderStatusForm, self).__init__(*args, **kwargs)
        self.fields['status'].widget.attrs['class'] = 'form-control'
        self.fields['status'].widget.attrs['style'] = 'width:200px'

templates/accounts/account_verification_email.html
{% autoescape off %}

Dear {{user.first_name | capfirst}},

Please click on below link to confirm your registration for JV Store account.

http://{{domain}}{% url 'activate' uidb64=uid token=token %}


Sincerely,
JV-STORE Team

{% endautoescape %}

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content py-3 bg footer-height">

	{% include 'includes/alerts.html' %}
	{% for field in form %}
				{% for error in field.errors %}
		<div class="alert alert-primary" role="alert">
			{{ error }}
		</div>
		{% endfor %}
		{% endfor %}
		{% if error_view %}
		<div class="alert alert-primary" role="alert">
		{{ error_view }}
		</div>
		{% endif %}
	<div class="row">

	{% include 'includes/dashboard_sidebar.html' %}

	<main class="col-md-10">
		<article class="card">
		<div class="card-body">

   <form action="{% url 'change_password' %}" method="POST">
     {% csrf_token %}
	      <div class="row gutters-sm">
					<div class="col-md-4 mb-3">
					  <div class="card">
					    <div class="card-body">
					      <div class="d-flex flex-column align-items-center text-center">
					        <img src="{{accounts.profile_pic.url}}" alt="Profile Picture" class="rounded-circle" style="width:150px;height:150px">
					        <div class="mt-3">
					          <h4>{{accounts.username}}</h4>
					          <p class="text-secondary mb-1">{{accounts.profession | title}}</p>
					          <p class="text-muted font-size-sm">{{accounts.address }}</p>
					        </div>

					      </div>
								<small class="text-danger">* password must contain at least 6 characters, 1 digit, uppercase, lowercase and symbol.</small>
					    </div>
					  </div>

					</div>

            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Old Password</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{form.old_password}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">New Password</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{form.new_password1}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Confirm New Password</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{form.new_password2}}
                    </div>
                  </div>
                  <hr>
                  <div class="form-group">
        			        <button type="submit" class="btn btn-primary btn-block"> Save Password </button>
        			    </div> <!-- form-group// -->
                </div>
              </div>
            </div>

          </div>
   </form>

		</div> <!-- card-body .// -->
		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/dashboard_single.html
{% extends 'base.html' %}
{% load static %}
{% load currency %}
{% load humanize %}
{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content py-3 bg footer-height">

	{% include 'includes/alerts.html' %}
	<div class="row">

	{% include 'includes/dashboard_sidebar.html' %}

	<main class="col-md-10">
		<article class="card">
			<div class="head-container">
				<div class="items">Total: {{count}} Item{{count | pluralize}} deleted and/or cancelled</div>
				<div class="items">Cancelled: {{cancel}}</div>

			</div>
		<div class="card-body overflow-auto">
			{% if not count %}
			<h3 class="text-center">You do not have Cancelled and Deleted Items.</h3>
			<br>
			<div class="text-center">
				<a href="{% url 'store' %}" class="btn btn-warning">Check the Store for Items that you might like.</a>
			</div>
			{% else %}
				<table class="table table-md">
					<thead>
						<tr>
							<th scope="col">Product</th>
							<th scope="col">Total Price</th>
							<th scope="col">Ordered</th>
							<th scope="col">Status</th>
							{% if user.is_admin %}
								<th scope="col">Action</th>
							{% endif %}
						</tr>
					</thead>
					<tbody>
						{% for order in orderproducts %}
						 <tr id="trcom{{order.id}}">
							 <td><a href="{% url 'order_detail' order.order.order_number %}">{{ order.payment}}</a>
								 <span class="d-block">{{ order.product.product_name}} <small class="ml-2 text-muted">{% for i in order.variation.all %} {{ i }} {% endfor %}</small></span>
								 <span class="d-block">{{order.user}}</span>
							 </td>
							 <td class="text-success b"> <span class="pr-1">{{order.order.currency}}</span> {{ order.total_price |currency:order.order.currency | intcomma }}</td>
							 <td>{{ order.date_updated}}</td>
							 <td>{{ order.status }}</td>

							 {% if user.is_admin %}
								 {% if order.status == 'Cancelled' %}
									 <td>
										 <form action="{% url 'update_status_cancel' order.order.order_number %}?ops={{order.product.slug}}" method="POST">
											 {% csrf_token %}
													<input type="hidden" name="cancel" value="cancelled">
													<button type="submit" class="btn btn-sm btn-info">Update</button>
										</td>
									{% elif order.status == 'PAID' or order.status == 'Done Refund' %}
										<form id="delcom{{order.id}}">
												<td>
													<input type="hidden" name="delo" value="delete_com">
													<button type="submit" style="outline-width: 0px !important"  class="btn btn-sm btn-danger" title="Delete this item?" id="subcom{{order.id}}">Delete item</button>
												</td>
										 </form>
										 <script type="text/javascript">
											$(function(){
												//ajax call here
											});

										 </script>
								 {% endif %}
								{% endif%}
						 </tr>
						{% endfor %}
					</tbody>
				</table>
			{% endif %}
		</div>

		</article>
	</main>
</div>

</section>


{% endblock %}

templates/accounts/forgotPassword_verification_email.html
{% autoescape off %}

  Dear {{ user.first_name }},

  To reset the password to your JV-STORE account, click the link below:

  http://{{ domain }}{% url 'forgotPasswordResetValidate' uidb64=uid token=token %}

  If the above link is not clickable, please copy the whole link and
  paste it in your browser.

  Sincerely,
  JV-STORE Team

{% endautoescape %}

templates/accounts/my_store_order.html
{% extends 'base.html' %}
{% load static %}
{% load currency %}
{% load humanize %}
{% block content %}

<section class="section-content py-3 bg footer-height">
	{% include 'includes/alerts.html' %}
	<div class="row">
	{% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-10">
		<article class="card">
		 <div class="head-container">
			 <div class="items">Total: {{count}} Item{{count | pluralize}}</div>
			 <div class="items">Pending: {{pending}}</div>
			 <div class="items">Sent: {{sent}}</div>
			 <div class="items">Cancelled: {{cancel}}</div>
			 <div class="items">For payment: {{for_payment_count}}</div>
		 </div>
		 <div class="footer-grid mb-4">
			 <div class="pt-2 item-footer">
				 {% if authorised %}
					 <p><b>For_payment</b> is when Customer confirm the payment and <b>Request_payment</b> is when the Seller manually confirm it.</p>
				 {% endif %}
			 </div>
			 <div class="d-flex m-2 pl-0 ml-0 ml-left">
			 Search by:
			 {% for fil in order_filter.form %}
			 <div class="items">
			 	 <span class="pr-1"> {{fil.name}}:</span><span> {{fil.value}} </span>
			 </div>
			 {% endfor %}
     </div>

			<div class="mb-4">
				<form method="GET" class="bg-light">
					{% csrf_token %}
					 <div class="d-flex justify-content-start m-2 pl-0 ml-0">
					 <label for="id_for_payment" class="pr-2">For payment</label>
					 <select name="for_payment" id="id_for_payment" class="form-control">
							<option value="unknown" selected="">Unknown</option>
							<option value="true">Yes</option>
							<option value="false">No</option>
						</select>
						<label for="id_request_payment" class="px-2">Request payment:</label>
 						<select name="request_payment" id="id_request_payment" class="form-control">
 							<option value="unknown" selected="">Unknown</option>
 							<option value="true">Yes</option>
 							<option value="false">No</option>
 						</select>
						 <label for="id_status" class="pr-2">Status</label>
							<select id="id_for_status" name="status">
								<option value="" selected="">---------</option>
								<option value="Pending">Pending</option>
								<option Value="Sent">Sent</option>
								<option Value="Cancelled">Cancelled</option>
							</select>
						<button class="btn btn-sm btn-warning ml-2" type="submit" style="height:36px">Search</button>
					 </div>
				</form>
			 </div>
				<script type="text/javascript">
					$(function(){
						$('label').addClass('px-2');
						$('select').addClass('form-control');
					})
				</script>

     <div class="card-body overflow-auto">
			{% if not count %}
			<h3 class="text-center">You do not have existing orders.</h3>
			<br>
			<div class="text-center">
				<a href="{% url 'store' %}" class="btn btn-warning">Check the Store for Items that you might like.</a>
			</div>
			{% else %}
				<table class="table table-md">
					<thead>
						<tr>
							<th scope="col">Transaction Detail</th>
							<th scope="col">Qty</th>
							<th scope="col">Total Price</th>
							<th scope="col">Status</th>

							{% if authorised %}
								<th scope="col">Update</th>
							{% endif %}
							<td scope="col">Item Delete and Monitoring</td>
              <td scope="col">Manual button (recieved)</td>
						</tr>
					</thead>
					<tbody>
						{% if authorised %}
							{% if currency == 'PHP' %}
								<span class="b text-muted">Total order amount:</span>  <span class="pl-1 text-warning b">{{total_amount | currency:currency  | intcomma }}</span> <span class="pl-1 text-success b">{{currency}}</span>
							{% else %}
									<span class="b text-muted">Total order amount:</span>  <span class="pl-1 text-warning b">{{total_amount | currency:currency  | intcomma }}</span> <span class="pl-1 text-success b">{{currency}}</span>
							{% endif %}
					  {% endif %}

						{% for order in orders %}
						 <tr>

							 <td><a href="{% url 'order_detail' order.order.order_number %}">{{ order.payment}}</a><span class="d-block">{{order.user}}</span><span class="d-block">{{ order}}</span><span class="d-block">{{ order.updated_at}}</span></td>
							  <td>{{order.quantity}}</td>

							  <td class="text-success b"> <span class="pr-1">{{order.order.currency}}</span> {{ order.total_price |currency:order.order.currency | intcomma }}</td>
							 <td>{{ order.status }}</td>

							 {% if authorised %}
									 {% if order.status == 'Sent' and order.recieved == True and order.paid == False %}
											 <td>
												<button type="submit" class="btn btn-sm btn-success" disabled>Waiting for payment</button>
											</td>
										{% elif order.paid == True and order.recieved == True %}
											<td>
											 <button type="submit" class="btn btn-sm btn-success">PAID</button>
										 </td>
										{% elif order.recieved == True and order.paid == False %}
 												<td>
 													 <!-- empty -->
 												</td>
 										{% elif order.status == 'Sent' or order.status == 'Cancelled' or order.status == 'Done Refund' %}
 												 <td>
 													 	<!-- empty -->
 												 </td>
 									  {% else %}
										 <td>
											 <a class="btn btn-sm btn-info" href="{% url 'update_order_status' order.payment %}?usr={{ order.user}}&trans={{ order.payment }}&pr={{order.product.slug}}">Update</a>
										 </td>
									 {% endif %}

									  {% if order.deleted != True %}
											  {% if order.paid == True or order.status == 'Done Refund' and order.status != 'Cancelled' %}
													<form id="del{{order.id}}">
														{% csrf_token %}
														 <td>
															 <input type="hidden" name="delo" value="deleted">
															 <button style="outline-width: 0px !important" type="submit" id="subdel{{order.id}}" class="btn btn-sm btn-danger" title="Customer deleted this item.">Delete item</button>
														 </td>
													</form>
														<script type="text/javascript">
													 $(function(){
														//ajax call
													 });
													</script>
													{% elif order.status == 'Cancelled' %}
													   <td>To process refund</td>
													{% endif %}

												{% if order.recieved == True %}
														{% if order.status == 'Sent' and order.paid == False %}
		 												 <td>
		 														<button type="button" class="btn btn-sm btn-success" title="item confirmed received" disabled>Received confirmed</button>
		 												 </td>
		 												{% endif %}

												{% elif order.status == 'Sent' %}
													<td>
														<button type="button" class="btn btn-sm btn-danger" title="item not yet acknowledged" disabled>Recieved not yet confirmed</button>
													</td>
											  {% endif %}

												{% if order.status == 'Sent' and order.order.order_number in order_list_days and not order.request_payment and not order.recieved %}
												<form id="{{order.id}}">
													 <td>
														 <input type="hidden" name="recieved" value="2">
														 <input type="hidden" name="cus" value="{{order.user}}">
														 <button style="outline-width: 0px !important" type="submit" id="sub{{order.id}}" class="btn btn-sm btn-secondary">Manual confirmed</button>
													 </td>
												 </form>
												 <script type="text/javascript">
													$(function(){
														//ajax call
													});
												 </script>
												 {% elif order.request_payment %}
												 <td>
														<button disabled type="button" class="btn btn-sm btn-danger">Manually Confirmed</button>
												 </td>
												{% endif %}
										 {% endif %}
							 {% endif %}
						 </tr>
						{% endfor %}
					</tbody>
				</table>
			{% endif %}
	  	</div>
		</article>
	</main>
</div>
</section>

{% endblock %}

templates/accounts/password_change_done.html
{% extends 'base.html' %}
{% load static %}

 {% block content %}
<script>
  $(document).ready(function(){
    window.location.href = '{% url "password_change" %}';
  });
</script>

{% endblock %}