carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('reduce_cart/<int:product_id>/<int:cart_item_id>/', views.reduce_cart, name='reduce_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

customer/urls.py
from django.urls import path

from . import views

app_name = 'customer'
urlpatterns = [
	# path('customer_search/', views.customer_search, name='customer_search'),
	path('list/<user_id>', views.friends_list_view, name='list'),
	path('friend_remove/', views.remove_friend, name='remove-friend'),
    path('friend_request/', views.send_friend_request, name='friend-request'),
    path('friend_request_cancel/', views.cancel_friend_request, name='friend-request-cancel'),
    path('friend_requests/<user_id>/', views.friend_requests, name='friend-requests'),
    path('friend_request_accept/<friend_request_id>/', views.accept_friend_request, name='friend-request-accept'),
    path('friend_request_decline/<friend_request_id>/', views.decline_friend_request, name='friend-request-decline'),
	# path('list/<user_id>', views.customer_search, name='search'),
]

shopme/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
import store


urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('passage/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('currencies/', include('currencies.urls')),
    path('chatapp/', include('chatapp.urls')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('seller/', views.seller_doc, name='seller_doc'),
    path('services/', views.services_doc, name='services_doc'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #for media folder files access

customer/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver

from chatapp.utils import find_or_create_private_chat
from notification.models import Notification


class FriendList(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user")
	friends = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="friends")

	# set up the reverse relation to GenericForeignKey
	notifications		= GenericRelation(Notification)

	def __str__(self):
		return self.user.username


	def add_friend(self, account):
		"""
		Add a new friend.
		"""
		if not account in self.friends.all():
			self.friends.add(account)
			self.save()

			content_type = ContentType.objects.get_for_model(self)

			# Create notification
			self.notifications.create(
				target=self.user,
				from_user=account,
				redirect_url=f"{settings.BASE_URL}/accounts/{account.pk}/",
				verb=f"You are now friends with {account.username}.",
				content_type=content_type,
			)
			self.save()

			# Create a private chat (or activate an old one)
			chat = find_or_create_private_chat(self.user, account)
			if not chat.is_active:
				chat.is_active = True
				chat.save()

    #remove friend from chat
	def remove_friend(self, account):
		"""
		Remove a friend.
		"""
		if account in self.friends.all():
			self.friends.remove(account)

			# Deactivate the private chat between these two users
			chat = find_or_create_private_chat(self.user, account)
			if chat.is_active:
				chat.is_active = False
				chat.save()


	def unfriend(self, removee):
		"""
		Initiate the action of unfriending someone.
		"""
		remover_friends_list = self # person terminating the friendship

		# Remove friend from remover friend list
		remover_friends_list.remove_friend(removee)

		# Remove friend from removee friend list
		friends_list = FriendList.objects.get(user=removee)
		friends_list.remove_friend(remover_friends_list.user)

		content_type = ContentType.objects.get_for_model(self)

		# Create notification for removee
		friends_list.notifications.create(
			target=removee,
			from_user=self.user,
			redirect_url=f"{settings.BASE_URL}/account/{self.user.pk}/",
			verb=f"You are no longer friends with {self.user.username}.",
			content_type=content_type,
		)

		# Create notification for remover
		self.notifications.create(
			target=self.user,
			from_user=removee,
			redirect_url=f"{settings.BASE_URL}/account/{removee.pk}/",
			verb=f"You are no longer friends with {removee.username}.",
			content_type=content_type,
		)

	@property
	def get_cname(self):
		"""
		For determining what kind of object is associated with a Notification
		"""
		return "FriendList"

	def is_mutual_friend(self, friend):
		"""
		Is this a friend?
		"""
		if friend in self.friends.all():
			return True
		return False



class FriendRequest(models.Model):
	"""
	A friend request consists of two main parts:
		1. SENDER
			- Person sending/initiating the friend request
		2. RECIVER
			- Person receiving the friend friend
	"""

	sender 				= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sender")
	receiver 			= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="receiver")

	is_active			= models.BooleanField(blank=False, null=False, default=True)

	timestamp 			= models.DateTimeField(auto_now_add=True)

	notifications		= GenericRelation(Notification)

	def __str__(self):
		return self.sender.username

	def accept(self):
		"""
		Accept a friend request.
		Update both SENDER and RECEIVER friend lists.
		"""
		print('pk1')
		is_receiver_friend_list = FriendList.objects.filter(user=self.receiver).exists()
		print('pk2')
		if is_receiver_friend_list:
			receiver_friend_list=FriendList.objects.get(user=self.receiver)
		# if receiver_friend_list:
			print('pk3')
			content_type = ContentType.objects.get_for_model(self)
			print('pk4')
			# Update notification for RECEIVER
			receiver_notification = Notification.objects.get(target=self.receiver, content_type=content_type, object_id=self.id)
			receiver_notification.is_active = False
			receiver_notification.redirect_url = f"{settings.BASE_URL}/accounts/{self.sender.pk}/"
			receiver_notification.verb = f"You accepted {self.sender.username}'s friend request."
			receiver_notification.timestamp = timezone.now()
			receiver_notification.save()
			print('pk5')
			receiver_friend_list.add_friend(self.sender)
			print('pk6')
			is_sender_friend_list = FriendList.objects.filter(user=self.sender).exists()

			if is_sender_friend_list:
				sender_friend_list = FriendList.objects.get(user=self.sender)
				print('pk7')
				# Create notification for SENDER
				self.notifications.create(
					target=self.sender,
					from_user=self.receiver,
					redirect_url=f"{settings.BASE_URL}/accounts/{self.receiver.pk}/",
					verb=f"{self.receiver.username} accepted your friend request.",
					content_type=content_type,
				)
				print('pk8')
				sender_friend_list.add_friend(self.receiver)
				# sender_friend_list.save()
				self.is_active = False
				self.save()
				print('pk9')
			else:
				print('pk100')
				# def __init__(self, *args, **kwargs):
				# 	super(FriendList, self).__init__(*args, **kwargs)
			    # self.fields['email'].widget.attrs['placeholder'] = 'Enter Email'
				print('pk100.1')
				#must create an instance first this is the proper way
				instance = FriendList.objects.create(user=self.sender)
				print('pk12k')
				instance.friends.set(self.receiver)
				# sender_friend_list = FriendList.objects.create(user=self.sender, friends=self.receiver)
				print('pk110')
				# Create notification for SENDER
				self.notifications.create(
					target=self.sender,
					from_user=self.receiver,
					redirect_url=f"{settings.BASE_URL}/accounts/{self.receiver.pk}/",
					verb=f"{self.receiver.username} accepted your friend request.",
					content_type=content_type,
				)
				print('pk120')
				sender_friend_list.add_friend(self.receiver)
				# sender_friend_list.save()
				self.is_active = False
				self.save()
				print('pk130')


		else:
			#create a friend list
			# receiver_friend_list = FriendList.objects.create(user=self.receiver, friends=self.sender)
			instance = FriendList.objects.create(user=self.sender)
			print('pk12k1')
			instance.friends.set(self.receiver)
			print('pk10')
			content_type = ContentType.objects.get_for_model(self)
			print('pk11')
			# Update notification for RECEIVER
			receiver_notification = Notification.objects.get(target=self.receiver, content_type=content_type, object_id=self.id)
			receiver_notification.is_active = False
			receiver_notification.redirect_url = f"{settings.BASE_URL}/accounts/{self.sender.pk}/"
			receiver_notification.verb = f"You accepted {self.sender.username}'s friend request."
			receiver_notification.timestamp = timezone.now()
			receiver_notification.save()
			print('pk12')
			receiver_friend_list.add_friend(self.sender)
			print('pk13')

			is_sender_friend_list = FriendList.objects.get(user=self.sender).exists()
			if is_sender_friend_list:
				sender_friend_list = FriendList.objects.get(user=self.sender, friends=self.receiver)
				print('pk14')
				# Create notification for SENDER
				self.notifications.create(
					target=self.sender,
					from_user=self.receiver,
					redirect_url=f"{settings.BASE_URL}/accounts/{self.receiver.pk}/",
					verb=f"{self.receiver.username} accepted your friend request.",
					content_type=content_type,
				)
				print('pk15')
				sender_friend_list.add_friend(self.receiver)
				# sender_friend_list.save()
				self.is_active = False
				self.save()
				print('pk16')

		return receiver_notification # we will need this later to update the realtime notifications


	def decline(self):
		"""
		Decline a friend request.
		Is it "declined" by setting the `is_active` field to False
		"""
		self.is_active = False
		self.save()

		content_type = ContentType.objects.get_for_model(self)

		# Update notification for RECEIVER
		notification = Notification.objects.get(target=self.receiver, content_type=content_type, object_id=self.id)
		notification.is_active = False
		notification.redirect_url = f"{settings.BASE_URL}/account/{self.sender.pk}/"
		notification.verb = f"You declined {self.sender}'s friend request."
		notification.from_user = self.sender
		notification.timestamp = timezone.now()
		notification.save()

		# Create notification for SENDER
		self.notifications.create(
			target=self.sender,
			verb=f"{self.receiver.username} declined your friend request.",
			from_user=self.receiver,
			redirect_url=f"{settings.BASE_URL}/account/{self.receiver.pk}/",
			content_type=content_type,
		)

		return notification


	def cancel(self):
		"""
		Cancel a friend request.
		Is it "cancelled" by setting the `is_active` field to False.
		This is only different with respect to "declining" through the notification that is generated.
		"""
		self.is_active = False
		self.save()

		content_type = ContentType.objects.get_for_model(self)

		# Create notification for SENDER
		self.notifications.create(
			target=self.sender,
			verb=f"You cancelled the friend request to {self.receiver.username}.",
			from_user=self.receiver,
			redirect_url=f"{settings.BASE_URL}/account/{self.receiver.pk}/",
			content_type=content_type,
		)

		notification = Notification.objects.get(target=self.receiver, content_type=content_type, object_id=self.id)
		notification.verb = f"{self.sender.username} cancelled the friend request sent to you."
		#notification.timestamp = timezone.now()
		notification.read = False
		notification.save()

	@property
	def get_cname(self):
		"""
		For determining what kind of object is associated with a Notification
		"""
		return "FriendRequest"

customer/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json

from accounts.models import Account
from customer.models import FriendRequest, FriendList


def friends_list_view(request, *args, **kwargs):
	context = {}
	user = request.user
	if user.is_authenticated:
		user_id = kwargs.get("user_id")
		if user_id:
			try:
				this_user = Account.objects.get(pk=user_id)
				context['this_user'] = this_user
			except Account.DoesNotExist:
				return HttpResponse("That user does not exist.")
			try:
				friend_list = FriendList.objects.get(user=this_user)
			except FriendList.DoesNotExist:
				return HttpResponse(f"Could not find a friends list for {this_user.username}")

			# Must be friends to view a friends list
			if user != this_user:
				if not user in friend_list.friends.all():
					return HttpResponse("You must be friends to view their friends list.")
			friends = [] # [(friend1, True), (friend2, False), ...]
			# get the authenticated users friend list
			auth_user_friend_list = FriendList.objects.get(user=user)
			for friend in friend_list.friends.all():
				friends.append((friend, auth_user_friend_list.is_mutual_friend(friend)))
			context['friends'] = friends

		# search functionality
		if request.method == "GET":
			search_query = request.GET.get("q")
			try:
				if len(search_query) > 0:
					search_results = Account.objects.filter(email__icontains=search_query).filter(username__icontains=search_query).distinct()
					user = request.user
					accounts = [] # [(account1, True), (account2, False), ...]
					if user.is_authenticated:
						# get the authenticated users friend list
						auth_user_friend_list = FriendList.objects.get(user=user)
						for account in search_results:
							accounts.append((account, auth_user_friend_list.is_mutual_friend(account)))
						context['accounts'] = accounts
					else:
						for account in search_results:
							accounts.append((account, False))
						context['accounts'] = accounts
			except:
				pass

	else:
		return HttpResponse("You must be friends to view their friends list.")
	return render(request, "customer/friend_list.html", context)

def friend_requests(request, *args, **kwargs):
	context = {}
	user = request.user
	if user.is_authenticated:
		user_id = kwargs.get("user_id")
		account = Account.objects.get(pk=user_id)
		if account == user:
			friend_requests = FriendRequest.objects.filter(receiver=account, is_active=True)
			context['friend_requests'] = friend_requests
		else:
			return HttpResponse("You can't view another users friend requets.")
	else:
		redirect("login")
	return render(request, "customer/friend_request.html", context)

def send_friend_request(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("receiver_user_id")
		if user_id:
			receiver = Account.objects.get(pk=user_id)
			try:
				# Get any friend requests (active and not-active)
				friend_requests = FriendRequest.objects.filter(sender=user, receiver=receiver)
				# find if any of them are active (pending)
				try:
					for request in friend_requests:
						if request.is_active:
							raise Exception("You already sent them a friend request.")
					# If none are active create a new friend request
					friend_request = FriendRequest(sender=user, receiver=receiver)
					friend_request.save()
					payload['response'] = "Friend request sent."
				except Exception as e:
					payload['response'] = str(e)
			except FriendRequest.DoesNotExist:
				# There are no friend requests so create one.
				friend_request = FriendRequest(sender=user, receiver=receiver)
				friend_request.save()
				payload['response'] = "Friend request sent."

			if payload['response'] == None:
				payload['response'] = "Something went wrong."
		else:
			payload['response'] = "Unable to sent a friend request."
	else:
		payload['response'] = "You must be authenticated to send a friend request."
	return HttpResponse(json.dumps(payload), content_type="application/json")

templates/customer/accept_friend_request.html
<script type="text/javascript">

	function acceptFriendRequest(friend_request_id, uiUpdateFunction){
		var url = "{% url 'customer:friend-request-accept' friend_request_id=53252623623632623 %}".replace("53252623623632623", friend_request_id)
		$.ajax({
			type: 'GET',
			dataType: "json",
			url: url,
			timeout: 5000,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "Friend request accepted."){
					// ui is updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			// error: function(data) {
			// 	console.error("ERROR...", data)
			// 	alert("Something went wrong.")
			// },
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}


</script>

templates/customer/cancel_friend_request.html
<script type="text/javascript">

	function cancelFriendRequest(id, uiUpdateFunction){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"receiver_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'customer:friend-request-cancel' %}",
			data: payload,
			timeout: 5000,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "Friend request canceled."){
					// ui is updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}


</script>

templates/customer/decline_friend_request.html
<script type="text/javascript">

	function declineFriendRequest(friend_request_id, uiUpdateFunction){
		var url = "{% url 'customer:friend-request-decline' friend_request_id=53252623623632623 %}".replace("53252623623632623", friend_request_id)
		$.ajax({
			type: 'GET',
			dataType: "json",
			url: url,
			timeout: 5000,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "Friend request declined."){
					// ui is updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}


</script>

templates/customer/friend_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content py-3 bg footer-height">

	<div class="px-3">
		{% include 'includes/alerts.html' %}
		{% for field in form %}
		{% for error in field.errors %}
		<div class="alert alert-primary" role="alert">
			{{ error }}
		</div>
		{% endfor %}
		{% endfor %}
		{% if error_view %}
		<div class="alert alert-primary" role="alert">
			{{ error_view }}
		</div>
		{% endif %}
		<div class="row">

			{% include 'includes/dashboard_sidebar.html' %}

			<main class="col-md-10 footer-height">
				<article class="card">
					<div class="card-body">
						<div class="row gutters-sm">
							<div class="col-md-4 mb-3">
								<div class="card">
									<div class="card-body">
										<div class="d-flex flex-column align-items-center text-center">
											<img src="{{request.user.profile_pic.url}}" alt="Profile Picture" class="img-md icon rounded-circle">
											<div class="mt-3">
												<p class="b mb-1">{{request.user.username}}</p>
												<p class="text-secondary mb-1">{{request.user.profession | title}}</p>
												<p class="text-muted font-size-sm">{{request.user.address }}</p>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-8">

								<!-- friend search starch here -->
								{% if accounts %}
								<h5 class="mr-3 font-weight-normal justify-content-start">
									<a class="pr-2 text-dark" href="#">Search Result</a>
								</h5>

								<div class="card p-2">
									<div class="d-flex flex-row flex-wrap">
										{% for account in accounts %}
										<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
											<a class="profile-link" href="{% url 'view' user_id=account.0.id %}">
												<div class="card-image m-2">
													<img class="img-fluid profile-image" src="{{account.0.profile_image.url}}" alt="">
												</div>
											</a>

												<div class="card-center px-2">
													<!-- <a class="profile-link" href="{% url 'view' user_id=account.0.id %}"> -->
													<a class="profile-link" href="#">
													  <h5>{{account.0.username}}</h5>
													</a>
													{% if account.1 %}
													<p class="card-text"><a href="#" onclick="createOrReturnPrivateChat('{{account.0.id}}')">Send a Message</a></p>
													{% endif %}
												</div>

											<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
												{% if account.1 %}
												<div class="d-flex flex-row friends-text-container p-3">
													<p class="friends-text m-auto">
														Friends
													</p>
													<span class="material-icons checkmark-icon m-auto pl-2">
														check_circle_outline
													</span>
												</div>
												{% else %}
												{% if account.0 !=  request.user %}
												<div class="d-flex flex-row friends-text-container p-3">
													<p class="friends-text m-auto">
														Not Friends
													</p>
													<span class="material-icons cancel-icon m-auto pl-2">cancel</span>
												</div>
												{% endif %}
												{% endif %}
												{% if account.0 == request.user %}
												<div class="d-flex flex-row friends-text-container p-3">
													<p class="friends-text m-auto">
														This is you
													</p>
													<span class="material-icons m-auto pl-2">
														person_pin
													</span>
												</div>
												{% endif %}
											</div>
										</div>
										{% if forloop.counter|divisibleby:2 %}
									</div>
									<div class="d-flex flex-row flex-wrap">
										{% endif %}
										{% endfor %}
									</div>
								</div>

								<!-- friend list starts here -->
								{% elif friends %}
								<div class="d-md-flex flex-row flex-grow-1 align-items-center mb-2">
									<h5 class="mr-3 font-weight-normal justify-content-start">
										<a class="pr-2 text-dark" href="#">Search Customer</a>
									</h5>
									<form class="search-bar justify-content-start" onsubmit="return executeQuery();">
										<input type="text" class="form-control" name="q" id="id_q_large" placeholder="Search...">
									</form>
								</div>

								<div class="card p-2">
									<div class="d-flex flex-row flex-wrap">
										{% for friend in friends %}
										<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
											<a class="profile-link" href="{% url 'view' user_id=friend.0.pk %}">
												<div class="card-image m-2">
													<img class="img-fluid profile-image" src="{{friend.0.profile_image.url}}" alt="">
												</div>
											</a>

											<div class="card-center px-2">
												<!-- <a class="profile-link" href="{% url 'view' user_id=friend.0.pk %}"> -->
												<a class="profile-link" href="#">
													<h5>{{friend.0.username|truncatechars:50}}</h5>
												</a>
												{% if friend.1 %}
												<a href="#" onclick="createOrReturnPrivateChat('{{friend.0.id}}')">Send a Message</a>
												{% endif %}

											</div>

											<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
												{% if friend.1 %}
												<div class="d-flex flex-row friends-text-container p-3">
													<p class="friends-text m-auto">
														Friends
													</p>
													<span class="material-icons checkmark-icon m-auto pl-2">
														check_circle_outline
													</span>
												</div>
												{% else %}
												{% if friend.0 !=  request.user %}
												<div class="d-flex flex-row friends-text-container p-3">
													<p class="friends-text m-auto">
														Not Friends
													</p>
													<span class="material-icons cancel-icon m-auto pl-2">cancel</span>
												</div>
												{% endif %}
												{% endif %}
												{% if friend.0 == request.user %}
												<div class="d-flex flex-row friends-text-container p-3">
													<p class="friends-text m-auto">
														This is you
													</p>
													<span class="material-icons m-auto pl-2">
														person_pin
													</span>
												</div>
												{% endif %}
											</div>
										</div>
										{% if forloop.counter|divisibleby:2 %}
									</div>
									<div class="d-flex flex-row flex-wrap">
										{% endif %}

										{% endfor %}

										{% else %}
										<!-- If no friends -->
										<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
											<p>No friends :(</p>
										</div>
									</div>

								</div>
								{% endif %}

							</div>


						</div>
					</div>
				</article> <!-- order-group.// -->
			</main>
		</div> <!-- row.// -->
	</div>


</section>
{%  include 'chatapp/create_or_return_private_chat.html' %}
<!-- ========================= SECTION CONTENT END// ========================= -->
<script>
	function executeQuery() {
		var query = ""
		if (query == "") {
			query = document.getElementById('id_q_large').value;
		}
		window.location.replace("{% url 'customer:list' request.user.id %}?q=" + query)
		return false
	}
</script>

{% endblock %}

templates/customer/friend_list0.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.friends-text{
		color: #000;
		font-weight: 500;
	}
	.friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after {
		content: none;
	}
	.profile-link{
		color: #000;
	}
	.checkmark-icon{
		color: green;
	}
	.cancel-icon{
		color: red;
	}

</style>

<div class="container">
	<div class="card p-2">

		{% if friends %}
		<div class="d-flex flex-row flex-wrap">
		{% for friend in friends %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<a class="profile-link" href="{% url 'view' user_id=friend.0.pk %}">
				<div class="card-image m-2">
					<img class="img-fluid profile-image" src="{{friend.0.profile_image.url}}" alt="">
				</div>
			</a>

			<div class="card-center px-2">
				<a class="profile-link" href="{% url 'view' user_id=friend.0.pk %}">
					<h4 class="card-title">{{friend.0.username|truncatechars:50}}</h4>
				</a>
				{% if friend.1 %}
				<a href="#" onclick="createOrReturnPrivateChat('{{friend.0.id}}')">Send a Message</a>
				{% endif %}

			</div>

			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
				{% if friend.1 %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							Friends
						</p>
						<span class="material-icons checkmark-icon m-auto pl-2">
						check_circle_outline
						</span>
					</div>
				{% else %}
					{% if friend.0 !=  request.user %}
						<div class="d-flex flex-row friends-text-container p-3">
							<p class="friends-text m-auto">
								Not Friends
							</p>
							<span class="material-icons cancel-icon m-auto pl-2">cancel</span>
						</div>
					{% endif %}
				{% endif %}
				{% if friend.0 == request.user %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							This is you
						</p>
						<span class="material-icons m-auto pl-2">
						person_pin
						</span>
					</div>
				{% endif %}
			</div>
		</div>
		{% if forloop.counter|divisibleby:2 %}
		</div><div class="d-flex flex-row flex-wrap">
		{% endif %}

		{% endfor %}

		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No friends :(</p>
		</div>
		{% endif %}
		</div>
	</div>

</div>

{%  include 'chatapp/create_or_return_private_chat.html' %}


{% endblock content %}

templates/customer/remove_friend.html
<script type="text/javascript">

	function removeFriend(id, uiUpdateFunction){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"receiver_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'customer:remove-friend' %}",
			timeout: 5000,
			data: payload,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "Successfully removed that friend."){
					// UI gets updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}


</script>

templates/customer/send_friend_request.html
<script type="text/javascript">

	function sendFriendRequest(id, uiUpdateFunction){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"receiver_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'customer:friend-request' %}",
			timeout: 5000,
			data: payload,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "Friend request sent."){
					// ui is updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}


</script>