carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('reduce_cart/<int:product_id>/<int:cart_item_id>/', views.reduce_cart, name='reduce_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

shopme/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
import store


urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('passage/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('currencies/', include('currencies.urls')),
    path('chatapp/', include('chatapp.urls')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('seller/', views.seller_doc, name='seller_doc'),
    path('services/', views.services_doc, name='services_doc'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #for media folder files access

store/urls.py
from django.urls import path, include
from . import views

urlpatterns = ([
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by-category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('price_search/', views.price_search, name='price_search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
    path('contact/', views.contact, name='contact'),
    path('update_product/<slug:product_slug>/', views.update_product, name='update_product'),
    path('add_product/', views.add_product, name='add_product'),
    path('delete_product/<slug:product_slug>/', views.delete_product, name='delete_product'),
    path('my_store/<str:seller>/', views.my_store, name='my_store'),
    path('liveSearch/', views.liveSearch, name='liveSearch'),
    path('add_delete_variation/<int:pk>', views.prodVariation, name='prodVariation' ),
])

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    # def __unicode__(self):
    #     return self.product

    def __str__(self):
        return self.product.product_name

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count
from django.template.defaultfilters import slugify
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill


class Product(models.Model):
    added_by        = models.ForeignKey(Account, blank=True, null=True, default=None, on_delete=models.CASCADE)
    product_name    = models.CharField(max_length=200, unique=True)
    slug            = models.SlugField(max_length=200, unique=True)
    description     = models.TextField(max_length=500, blank=True)
    price           = models.IntegerField()
    images          = models.ImageField(upload_to='photos/products', default="userprofile/bugambilaya.jpg")
    image_thumbnail = ImageSpecField(source='images', processors=[ResizeToFill(480, 600)], format = 'JPEG', options = {'quality':60})
    stock           = models.IntegerField()
    sold            = models.IntegerField(default=0)
    is_available    = models.BooleanField(default=True)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date    = models.DateTimeField(auto_now_add=True)
    modified_date   = models.DateTimeField(auto_now=True)
    is_digital      = models.BooleanField(default=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])
    #
    def __str__(self):
        return self.product_name

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg=0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count=0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.product_name)
        return super().save(*args, **kwargs)

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choice=(
    ('color','color'),
    ('size','size'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=200, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True) #so that the variation can be disabled
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager() #telling Variation that there is a variation manager function for it

    def __str__(self):
        return self.variation_value

class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=102, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField(default=5)
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.product

class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255, default=None, blank=True)
    image_thumbnail = ImageSpecField(source='image', processors=[ResizeToFill(150, 150)], format = 'JPEG', options = {'quality':60})

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from orders.models import Order
from accounts.models import Account
from accounts.forms import CheckoutForm
from currencies.models import Currency
from django.contrib import messages

# Create your views here.
def _cart_id(request): #underscore means that it is private
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)
    stock = product.stock

    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            #the csrf token is included with its key so we need to explicitely define the keys to find which are size and color or we can start the counting to 1 not zero.
            for item in request.POST:
                key = item
                value = request.POST[key]
                keys = ['color', 'size']
                if key not in keys:
                    continue
                else:
                    try:
                        variation = Variation.objects.get(product=product, variation_category__iexact = key, variation_value__iexact=value)
                        product_variation.append(variation)
                    except Exception as e: #caching the error to continue processing the code
                        messages.warning(request, "There was an error. {}".format(str(e)))

        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            existing_variation_list = []
            id_list = []
            # getting the existing variation
            for item in cart_item:
                existing_variation = item.variations.all()
                existing_variation_list.append(list(existing_variation))
                id_list.append(item.id)

            # checking new cart item to existing variation
            if product_variation in existing_variation_list:
                index = existing_variation_list.index(product_variation)
                item_id = id_list[index]
                item = CartItem.objects.get(product=product, id=item_id)

                item.quantity += 1
                # check the avilability of the stock
                stock = product.stock
                if (stock-item.quantity) < 0:
                    messages.warning(request, f'You can get only {item.quantity-1}. The stock of {product.product_name} runs out of items already')
                    return redirect('cart')
                else:
                    item.save()

            else:
                #create but if there is variation clear it so they will not mix and just preserve the last one
                item =CartItem.objects.create(product = product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()

        else: #this is to create an initial item if nothing yet is in the cart (initiator)
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                user = current_user, #the session key
            )

            #to prevent mixing variations on the manytomanyfield
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)

            # check the avilability of the stock
            stock = product.stock
            if (stock-cart_item.quantity) < 0:
                messages.warning(request, f'You can get only {cart_item.quantity-1}. The stock of {product.product_name} runs out of items already')
                return redirect('cart')
            else:
                cart_item.save()
        return redirect('cart')

    #if user is not authenticated
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                keys = ['color', 'size']
                if key not in keys:
                    continue
                else:
                    try:
                        variation = Variation.objects.get(product=product, variation_category__iexact = key, variation_value__iexact=value)
                        product_variation.append(variation)
                    except Exception as e: #caching the error to continue processing the code
                        messages.warning(request, "There was an error. {}".format(str(e)))

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request)) #get the cart using the cart_id in the sesiion
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            #existing variation
            #current variation
            #item id
            existing_variation_list = []
            id_list = []
            for item in cart_item:
                existing_variation = item.variations.all()
                existing_variation_list.append(list(existing_variation))
                id_list.append(item.id)

            if product_variation in existing_variation_list:
                #just increase
                index = existing_variation_list.index(product_variation)
                item_id = id_list[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1

                # check the avilability of the stock
                stock = product.stock
                if (stock-item.quantity) < 0:
                    messages.warning(request, f'You can get only {item.quantity-1}. The stock of {product.product_name} runs out of items already')
                    return redirect('cart')
                else:
                    item.save()

            else:
                #create
                item =CartItem.objects.create(product = product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()

        else: #this is to create an initial item if nothing yet is in the cart (initiator)
            item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart,
            )

            if len(product_variation) > 0:
                item.variations.clear()
                item.variations.add(*product_variation)

            # check the avilability of the stock
            stock = product.stock
            if (stock-item.quantity) < 0:
                messages.warning(request, f'You can get only {item.quantity}. The stock of {product.product_name} runs out of items already')
                return redirect('cart')
            else:
                item.save()
        return redirect('cart')

def reduce_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)

    if request.user.is_authenticated:
        try:
            cart_item = CartItem.objects.get(user=request.user, id=cart_item_id)
            #make a condition
            if cart_item.quantity > 1:
                cart_item.quantity -=1
                cart_item.save()
            else:
                cart_item.delete()
        except:
            pass
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request)) #if user is not authenticated
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -=1
            cart_item.save()
        else:
            cart_item.delete()

    return redirect('cart')

def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        try:
            cart_item = CartItem.objects.get(user=request.user, id=cart_item_id)
        except:
            pass
    else:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        #inititalize the variable first
        tax=0
        grand_total=0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
            for cart_item in cart_items:
                total+=(cart_item.product.price*cart_item.quantity)
                quantity+=cart_item.quantity
            tax = (8 * total)/100
            grand_total = total #tax included in the markup
            grand_total = '{:.2f}'.format(float(grand_total))

        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

            for cart_item in cart_items:
                total+=(cart_item.product.price*cart_item.quantity)
                quantity+=cart_item.quantity
            tax = (8 * total)/100
            grand_total = total #tax included in the markup
            grand_total = '{:.2f}'.format(float(grand_total))

templates/store/add_delete_variation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content py-3 bg footer-height" id="add_main">
	{% include 'includes/alerts.html' %}
	<div class="row">
	<main class="col-md-12">
		<article class="card">
		<div class="card-body">
   <form action="{% url 'prodVariation' prod_id %}" method="POST">
     {% csrf_token %}
      <div class="row gutters-sm">
					 {% include 'includes/dashboard_sidebar.html' %}
							 <div class="col-md-10 mb-3">
								 <div class="card">
									 <div class="card-body">
                     <h5 class="d-inline-block">Add Variation:</h5>
                      <hr>
 	                  <div class="row">
 	                    <div class="col-sm-4">
 	                      <h6 class="mb-0">Product</h6>
 	                    </div>
 	                    <div class="col-sm-8 text-secondary">
												<input type="text" name="product" value="{{product}}" id="id_product">
 	                    </div>
 	                  </div>
 										<hr>
                    <div class="row">
 	                    <div class="col-sm-4">
 	                      <h6 class="mb-0">variation_category</h6>
 	                    </div>
 	                    <div class="col-sm-8 text-secondary">
												{{form.variation_category}}
 	                    </div>
 	                  </div>
 										<hr>
                    <div class="row mb-2">
 	                    <div class="col-sm-4">
 	                      <h6 class="mb-0">variation_value</h6>
 	                    </div>
 	                    <div class="col-sm-8 text-secondary">
												{{form.variation_value}}
 	                    </div>
 	                  </div>

 	                  <div class="form-group">
 	        			        <button type="submit" class="btn btn-warning btn-block col-md-4 float-right" id="apply_changes"> Add </button>
 	        			    </div>
									 </div>
								 </div>
							 </div>
						 </div>
					 </form>

				   <form action="{% url 'prodVariation' prod_id %}" method="POST">
				     {% csrf_token %}
				      <div class="row gutters-sm">
								<aside class="col-md-2">
									<!-- dummy tag -->
								 </aside>
				              <div class="col-md-10 mb-3">
				                <div class="card">
				                  <div class="card-body">
				                     <h5 class="d-inline-block">Delete Variation:</h5>
				                      <hr>
				                     <div class="row">
				                       <div class="col-sm-4">
				                         <h6 class="mb-0">Product Name:</h6>
				                         <input type="text" id="id_products" name="product" value="{{product}}">
				                       </div>
				                       <div class="col-sm-8 text-secondary">
				                         {% if product.variation_set.colors %}
				                         <h6>Select Color</h6>
				                         <select name="color" class="form-control">
				                          <option value="" diabled selected>select</option>
				                            {% for i in product.variation_set.colors %}
				                              <option value="{{i.variation_value}}">{{i.variation_value | capfirst}}</option>
				                            {% endfor %}
				                          </select>
				                         {% endif %}
				                         <br>
				                         {% if product.variation_set.sizes %}
				                         <h6>Select Size</h6>
				                         <select name="size" class="form-control">
				                          <option value="" diabled selected>select</option>
				                            {% for i in product.variation_set.sizes %}
				                              <option value="{{i.variation_value}}">{{i.variation_value | capfirst}}</option>
				                            {% endfor %}
				                          </select>
				                         {% endif %}
				                       </div>
				                     </div>
				                     <hr>

				                     <div class="form-group">
				                         <button type="submit" class="btn btn-danger btn-block col-md-4 float-right" id="apply_changes"> Delete </button>
				                     </div>
				                  </div>
				                </div>
				              </div>
				          </div>
				   </form>

	   <div class="text-secondary text-center">
	     <h6>Variation List</h6>
	     {% if product.variation_set.colors %}
	     <h6>Avialable Color{% if product.variation_set.colors.count > 1 %}{{ product.variation_set.colors | pluralize:'s'}} {% endif %}</h6>
	        {% for i in product.variation_set.colors %}
	          ({{ i.variation_value | capfirst }})
	        {% endfor %}
	     {% endif %}
	     <br>
	     {% if product.variation_set.sizes %}
	     <h6>Available Size{% if product.variation_set.sizes.count > 1 %}{{ product.variation_set.sizes | pluralize:'s'}} {% endif %}</h6>
	        {% for i in product.variation_set.sizes %}
	          ({{i.variation_value | capfirst}})
	        {% endfor %}
	     {% endif %}
	   </div>

		</div>
		</article>
	</main>
</div>

</section>
<script>
	$(document).ready(function(){
		add_gotoMain();
	});
</script>
{% endblock %}

templates/store/add_product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content py-3 bg footer-height">
	{% include 'includes/alerts.html' %}
	<div class="row">
	{% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-10">
		<article class="card">
		<div class="card-body">
   <h5 class="d-inline-block">Add product page:</h5>
   <form action="{% url 'add_product' %}" method="POST" enctype="multipart/form-data" novalidate>
     {% csrf_token %}
      <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center" id="id_image_container">
                    <div class="mt-3">
												<div class="middle" id="id_middle_container">

												{{ formset.management_form }}
													{{productImage.errors}}
													{{productImage.as_p }}
													{% for form in formset %}
													      {{form}}
													   {% endfor %}
														<h6 class="mt-3">Product Images</h6>
												</div>
                    </div>
                  </div>
                </div>
              </div>

            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">

									<div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Store Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{info | title}} Store
                    </div>
                  </div>
                  <hr>

                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Product Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{form.product_name}}
                    </div>
                  </div>
									<hr>

                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Description</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{form.description}}
                    </div>
                  </div>
                  <hr>
									<div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Price</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{form.price}}
											<span class="d-block float-right"><small class="text-danger float-right"><em>*base is Philippine Peso*</em></small></span>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Stock</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{form.stock}}
                    </div>
                  </div>
                  <hr>
									<div class="row">
										<div class="col-sm-3">
											<h6 class="mb-0">Category</h6>
										</div>
										<div class="col-sm-9 text-secondary">
											{{form.category}}
										</div>
									</div>
									<hr>
									<div class="row">
										<div class="col-sm-3">
											<h6 class="mb-0">Digital Product</h6>
										</div>
										<div class="col-sm-9 text-secondary">
											{{form.is_digital}}
										</div>
									</div>
									<hr>
                  <div class="form-group">
        			        <button type="submit" class="btn btn-warning btn-block" id="apply_changes"> Submit </button>
        			    </div>
                </div>
              </div>
            </div>
          </div>
       </form>
		</div>
		</article>
	</main>
</div>
</section>
<script>
	// for digital prod
	$(function(){
		$('li').css({'list-style':'none'})
	})
</script>
{% endblock %}

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% load currency %}
{% load humanize %}
{% block content %}
<section class="section-content padding-y bg footer-height">
	<div class="container">
		{% include 'includes/alerts.html' %}
		{% if not cart_items %}
		<h3 class="text-center">Your shopping cart is empty</h3>
		<br>
		<div class="text-center">
			<a href="{% url 'store' %}" class="btn btn-warning">Continue Shopping</a>
		</div>
		{% else %}
		<div class="row">
			<aside class="col-lg-9">
				<div class="card">
					<table class="table table-borderless table-shopping-cart">
						<thead class="text-muted">
							<tr class="small text-uppercase">
								<th scope="col">Product</th>
								<th scope="col">Quantity</th>
								<th scope="col">Price</th>
							</tr>
						</thead>
						<tbody>
							{% for cart_item in cart_items %}
							<tr>
								<td>
									<figure class="itemside align-items-center">
										<div class="aside"><a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.images.url}}" class="img-sm"></a></div>
										<figcaption class="info">
											<a href="{{cart_item.product.get_url}}" class="title text-dark">{{cart_item.product.product_name}}</a>
											<p class="text-muted small">
												{% if cart_item.variations.all %}
												{% for item in cart_item.variations.all %}
												{{item.variation_category | capfirst}} :{{item.variation_value}} <br>
												{% endfor %}
												{% endif %}
											</p>
										</figcaption>
									</figure>
								</td>
								<td>
									<div class="col">
										<div class="input-group input-spinner">

											<div class="input-group-prepend" title='delete'>
												<a href="{% url 'reduce_cart' cart_item.product_id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
											</div>
									 {% if cart_item.product.category.category_name != 'eproduct' %}
											<input type="text" class="form-control-quantity" value="{{cart_item.quantity}}">
											<div class="input-group-append">
												<form action="{% url 'add_cart' cart_item.product_id %}" method="POST">
													{% csrf_token %}
													<!--get the set of variation-->
													{% for item in cart_item.variations.all %}
													<input type="hidden" name="{{item.variation_category | lower}}" value="{{item.variation_value | capfirst}}">
													{% endfor %}
													<button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
												</form>
											</div>
										{% else %}
										   <input type="text" class="form-control-quantity text-justify border-0" disabled value="{{cart_item.quantity}}">
                    {% endif %}
										</div>
									</div>
								</td>
								<td>
									<div class="price-wrap">
										<var class="price text-primary">{{symbol}}{{ cart_item.sub_total|currency:currency | intcomma }}</var>
										<small class="text-muted">{{symbol}}{{ cart_item.product.price|currency:currency }} each </small>
									</div>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div> 
			</aside>
			<aside class="col-lg-3">
				<div class="card">
					<div class="card-body">
						<dl class="dlist-align">
							<dt>Total price:</dt>
							<dd class="text-right text-primary">{{symbol}}{{ total|currency:currency | intcomma }}</dd>
						</dl>
						<dl class="dlist-align">
							<dt>Grand Total:</dt>
							<dd class="text-right b text-warning"><strong>{{symbol}}{{ grand_total|currency:currency | intcomma }}</strong></dd>
						</dl>
						<hr>
						<p class="text-center mb-3">
							<img src="{% static './images/misc/payments.png' %}" height="26">
						</p>
						<a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
						<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
					</div>
				</div>
			</aside>
		</div>
		{% endif %}
	</div>
</section>
{% endblock %}

templates/store/contact_us_email.html
{% autoescape off %}
Name: {{first_name | title}}
Client email: {{email}}
Message: {{message}}


{% endautoescape %}